### ISSUE TITLE
Map over sidebar/navbar

### ISSUE THREAD

**Issue by LukeSavefrogs** [dotswan/filament-map-picker#98]
Hi, it's me again 😄 

## Problem

The maps (both the `Infolists\MapEntry` and the `Fields\Map`) seem to overlap the navbar, preventing the user from clicking on anything else:

![Image](https://github.com/user-attachments/assets/ab551d42-6f1a-4c5f-b7ad-4033d1435ed3)

## Workaround

To fix I placed the following CSS in my `resources/css/app.css` (vite theme):
```css
/* Override for `Dotswan\MapPicker\*` */
div[x-ref="map"] {
    z-index: 0 !important;
}
```

![Image](https://github.com/user-attachments/assets/7b819aa9-4e39-407e-9182-d4d914ddeabd)
